name: Release

on:
  release:
    types: [published]
    branches:
      - "main"

jobs:
  release:
    name: Release
    uses: molssi-seamm/devops/.github/workflows/Release.yaml@main
    with:
      src : mopac_step
    secrets: inherit

  docker:
    name: Docker
    needs: release
    uses: molssi-seamm/devops/.github/workflows/Docker.yaml@main
    with:
      image : molssi-seamm/seamm-mopac
    secrets: inherit
